name: vavuniya_ads
description: 'A new Flutter project.'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.0.0
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^0.22.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  provider: ^6.1.2
  get: ^4.6.5
  http: ^1.1.0
  carousel_slider: ^5.0.0
  share_plus: ^7.0.0
  image_picker: ^1.0.4
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.5.2
  flutter_debouncer: ^2.0.0
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
