name: vavuniya_ads
description: 'A new Flutter project.'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.0.0
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
